"""Centralized V1 learning-engine constants."""

P0 = 0.35
PL = 0.05
PS = 0.20
DEFAULT_PG = 0.20

UNDERSTANDING_ALPHA = 0.35

OBJECTIVE_WEIGHT = 0.75
UNDERSTANDING_WEIGHT = 0.25

QUESTION_NEED_OLD_WEIGHT = 0.60
QUESTION_NEED_NEW_WEIGHT = 0.40

MAX_ATTEMPTS_PER_QUESTION_PER_SESSION = 3
MIN_INTERVENING_QUESTIONS = 4

MASTERY_THRESHOLD = 0.95
MIN_MASTERY_ATTEMPTS = 3
MIN_DISTINCT_MASTERY_QUESTIONS = 2

RECENCY_HORIZON_DAYS = 14

EXPLORATION_FLOOR = 0.05
